# Generated by Django 4.2.7 on 2026-02-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_enhance_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="crop",
            new_name="monitor_cro_farm_id_f3056d_idx",
            old_name="monitor_cro_farm_id_idx",
        ),
        migrations.RenameIndex(
            model_name="crop",
            new_name="monitor_cro_crop_ty_a1ff10_idx",
            old_name="monitor_cro_crop_ty_idx",
        ),
        migrations.RenameIndex(
            model_name="farm",
            new_name="monitor_far_farmer__878f1a_idx",
            old_name="monitor_far_farmer__idx",
        ),
    ]
